const HOME = "/",
  LOADING = "/loading",
  QUESTION = "/question",
  RESULT = "/result",
  ESTJ = "/wrestling",
  ISTJ = "/judo",
  ESFJ = "/taekwondo",
  ISFJ = "/hapkido",
  ESTP = "/mma",
  ISTP = "/boxing",
  ESFP = "/wushu",
  ISFP = "/kendo",
  ENTJ = "/kravmaga",
  INTJ = "/archery",
  ENFJ = "/taichi",
  INFJ = "/aikido",
  ENTP = "/jiujitsu",
  INTP = "/fencing",
  ENFP = "/capoeira",
  INFP = "/baguazhang";

const routes = {
  home: HOME,
  loading: LOADING,
  question: QUESTION,
  result: RESULT,
  estj: ESTJ,
  istj: ISTJ,
  esfj: ESFJ,
  isfj: ISFJ,
  estp: ESTP,
  istp: ISTP,
  esfp: ESFP,
  isfp: ISFP,
  entj: ENTJ,
  intj: INTJ,
  enfj: ENFJ,
  infj: INFJ,
  entp: ENTP,
  intp: INTP,
  enfp: ENFP,
  infp: INFP,
};

export default routes;
